-- MySQL Script generated by MySQL Workbench
<<<<<<< HEAD
-- Fri Aug 12 12:39:46 2016
=======
-- Fri Aug  5 11:54:28 2016
>>>>>>> origin/master
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema saishibao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saishibao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saishibao` DEFAULT CHARACTER SET utf8 ;
USE `saishibao` ;

-- -----------------------------------------------------
-- Table `saishibao`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(30) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `realName` VARCHAR(20) NOT NULL,
  `rickName` VARCHAR(20) NULL,
  `idCard` VARCHAR(30) NULL,
  `passportID` VARCHAR(30) NULL,
  `oneWayPermit` VARCHAR(30) NULL COMMENT '港澳通行证\n',
  `userPoint` INT NOT NULL,
  `user_spell` VARCHAR(50) NULL,
<<<<<<< HEAD
  `mobile` VARCHAR(20) NULL COMMENT '手机号',
=======
>>>>>>> origin/master
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`country` (
  `country_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL COMMENT '国家',
<<<<<<< HEAD
  `continent` VARCHAR(30) NOT NULL COMMENT '洲名',
  `image_url` VARCHAR(255) NULL COMMENT '国旗url地址',
=======
>>>>>>> origin/master
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC))
ENGINE = InnoDB
COMMENT = '俱乐部所在国家';


-- -----------------------------------------------------
-- Table `saishibao`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`city` (
  `city_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL COMMENT '城市',
<<<<<<< HEAD
  `city_en` VARCHAR(50) NULL COMMENT '城市英文名',
=======
>>>>>>> origin/master
  `country_id` INT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `saishibao`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '俱乐部所在城市';


-- -----------------------------------------------------
-- Table `saishibao`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`address` (
  `address_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(60) NOT NULL COMMENT '详细地址',
  `city_id` INT UNSIGNED NOT NULL,
  `longitude` DECIMAL(10,7) NULL COMMENT '经度',
  `latitude` DECIMAL(10,7) NULL COMMENT '纬度',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `saishibao`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '俱乐部详细地址';


-- -----------------------------------------------------
-- Table `saishibao`.`casino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`casino` (
  `casino_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `casino` VARCHAR(50) NOT NULL COMMENT '俱乐部名称',
  `address_id` INT UNSIGNED NOT NULL,
  `open_time` TIME NOT NULL COMMENT '营业开始时间\n',
  `close_time` TIME NOT NULL COMMENT '营业结束时间',
<<<<<<< HEAD
  `logo_url` VARCHAR(255) NULL COMMENT '俱乐部logo 的 url地址',
  `contact_phone` VARCHAR(30) NULL,
  `contact_person` VARCHAR(30) NULL COMMENT '联系人',
  `intorduction` TEXT NULL COMMENT '俱乐部介绍',
  `web_url` VARCHAR(255) NULL COMMENT '俱乐部网址',
=======
  `logo_url` VARCHAR(45) NULL COMMENT '俱乐部logo 的 url地址',
  `contact_phone` VARCHAR(30) NULL,
  `contact_person` VARCHAR(30) NULL COMMENT '联系人',
  `intorduction` TEXT NULL COMMENT '俱乐部介绍',
>>>>>>> origin/master
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`casino_id`),
  INDEX `fk_casino_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_casino_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `saishibao`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '俱乐部信息';


-- -----------------------------------------------------
-- Table `saishibao`.`casinoImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`casinoImage` (
  `casinoImage_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL COMMENT '图片url地址',
  `casino_casino_id` INT UNSIGNED NOT NULL,
  `remark` VARCHAR(50) NULL DEFAULT '备注',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`casinoImage_id`),
  INDEX `fk_casinoImage_casino1_idx` (`casino_casino_id` ASC),
  CONSTRAINT `fk_casinoImage_casino1`
    FOREIGN KEY (`casino_casino_id`)
    REFERENCES `saishibao`.`casino` (`casino_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '图片存放路径表';


-- -----------------------------------------------------
-- Table `saishibao`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`feature` (
  `feature_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `feature` VARCHAR(50) NOT NULL COMMENT '特色',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`feature_id`))
ENGINE = InnoDB
COMMENT = '俱乐部特色';


-- -----------------------------------------------------
-- Table `saishibao`.`casino_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`casino_feature` (
  `feature_id` INT UNSIGNED NOT NULL,
  `casino_id` INT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`feature_id`, `casino_id`),
  INDEX `fk_casino_feature_casino1_idx` (`casino_id` ASC),
  INDEX `fk_casino_feature_feature1_idx` (`feature_id` ASC),
  CONSTRAINT `fk_casino_feature_feature1`
    FOREIGN KEY (`feature_id`)
    REFERENCES `saishibao`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_casino_feature_casino1`
    FOREIGN KEY (`casino_id`)
    REFERENCES `saishibao`.`casino` (`casino_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'casino_feature联结表';


-- -----------------------------------------------------
<<<<<<< HEAD
-- Table `saishibao`.`matchSetting_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`matchSetting_copy1` (
  `matchSetting_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`matchSetting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
=======
>>>>>>> origin/master
-- Table `saishibao`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`organization` (
  `organization_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `casino_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '赛事组织者名称，国内常规赛的名称＝俱乐部名称',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`organization_id`),
  INDEX `fk_organization_casino1_idx` (`casino_id` ASC),
  CONSTRAINT `fk_organization_casino1`
    FOREIGN KEY (`casino_id`)
    REFERENCES `saishibao`.`casino` (`casino_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '赛事组织者';


-- -----------------------------------------------------
<<<<<<< HEAD
-- Table `saishibao`.`bigMatchTour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`bigMatchTour` (
  `bigMatchTour_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL COMMENT '巡回赛名称',
  PRIMARY KEY (`bigMatchTour_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
=======
>>>>>>> origin/master
-- Table `saishibao`.`bigMatchSerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`bigMatchSerie` (
  `bigMatchSerie_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL COMMENT '系列赛名称',
  `type` TINYINT NOT NULL COMMENT '赛事类型\n1:国际\n2:国内\n3:俱乐部大赛',
<<<<<<< HEAD
  `is_tour` TINYINT(1) NOT NULL COMMENT '是否属于巡回赛',
  `bigMatchTour_id` INT UNSIGNED NULL,
  `tour_image` VARCHAR(45) NULL,
  `image_url` VARCHAR(255) NULL COMMENT '推荐图片的url',
  `intro_image_url` VARCHAR(255) NULL COMMENT '介绍页图片的url',
  `intro_title` VARCHAR(20) NULL COMMENT '介绍页标题',
  `intro_content` TEXT NULL COMMENT '介绍页内容',
=======
  `is_serie` TINYINT(1) NOT NULL COMMENT '是否属于系列赛',
  `image_url` VARCHAR(255) NOT NULL COMMENT '推荐图片的url',
  `intro_image_url` VARCHAR(255) NOT NULL COMMENT '介绍页图片的url',
  `intro_title` VARCHAR(20) NOT NULL COMMENT '介绍页标题',
  `intro_content` TEXT NOT NULL COMMENT '介绍页内容',
>>>>>>> origin/master
  `hot_level` TINYINT NOT NULL DEFAULT 5 COMMENT '推荐等级：\n1最高，依次 2 3 4，默认5',
  `need_show` TINYINT(1) NOT NULL COMMENT '1:显示在app\n0:不显示',
  `start_date` DATE NOT NULL COMMENT '赛事开始日期',
  `end_date` DATE NOT NULL COMMENT '赛事结束日期',
  `cooperated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否有商务合作\n0,未合作\n1，合作',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bigMatchSerie_id`),
  INDEX `fk_bigMatchSerie_organization1_idx` (`organization_id` ASC),
<<<<<<< HEAD
  INDEX `fk_bigMatchSerie_bigMatchTour1_idx` (`bigMatchTour_id` ASC),
=======
>>>>>>> origin/master
  CONSTRAINT `fk_bigMatchSerie_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `saishibao`.`organization` (`organization_id`)
    ON DELETE NO ACTION
<<<<<<< HEAD
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bigMatchSerie_bigMatchTour1`
    FOREIGN KEY (`bigMatchTour_id`)
    REFERENCES `saishibao`.`bigMatchTour` (`bigMatchTour_id`)
    ON DELETE NO ACTION
=======
>>>>>>> origin/master
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '大赛系列';


-- -----------------------------------------------------
-- Table `saishibao`.`matchSetting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`matchSetting` (
  `matchSetting_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '设置名称',
  `structure` TEXT NOT NULL COMMENT '赛事结构 json',
  `bonus` TEXT NOT NULL COMMENT '赛事奖金 json',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`matchSetting_id`))
ENGINE = InnoDB
COMMENT = '奖金和比赛结构设置';


-- -----------------------------------------------------
-- Table `saishibao`.`exchangeRate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`exchangeRate` (
  `exchangeRate_id` INT ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(20) NOT NULL COMMENT '货币名称',
  `exchange_rate` DECIMAL(7,3) NOT NULL COMMENT '与人民币汇率',
  `currency_code` VARCHAR(20) NULL COMMENT '货币代码',
  `last_update` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`exchangeRate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`bigMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`bigMatch` (
  `bigMatch_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bigMatchSerie_id` INT UNSIGNED NOT NULL,
  `matchSetting_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL COMMENT '赛事名称',
  `real_buyin` DECIMAL(10,2) NOT NULL COMMENT '真实buy-in',
  `rake_buyin` DECIMAL(10,2) NOT NULL COMMENT 'rake buy-in',
<<<<<<< HEAD
=======
  `need_exchange` TINYINT(1) NOT NULL COMMENT '是否需要兑换为人民币\n1:兑换\n0:不兑换',
>>>>>>> origin/master
  `match_day` DATE NOT NULL COMMENT '比赛日',
  `open_time` TIME NOT NULL COMMENT '开始时间',
  `close_reg_time` TIME NOT NULL COMMENT '关闭注册',
  `can_register` TINYINT(1) NOT NULL COMMENT '是否可以报名',
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT '单笔报名费（rmb）',
<<<<<<< HEAD
  `need_exchange` TINYINT(1) NOT NULL COMMENT '是否需要兑换为人民币\n1:兑换\n0:不兑换',
  `exchangeRate_id` INT UNSIGNED NULL,
  `state` TINYINT NOT NULL COMMENT '赛事状态',
  `style` VARCHAR(30) NOT NULL COMMENT '比赛类型',
  `remark` VARCHAR(50) NULL COMMENT '备注信息',
=======
  `exchangeRate_id` INT UNSIGNED NOT NULL,
  `state` TINYINT NOT NULL COMMENT '赛事状态',
>>>>>>> origin/master
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bigMatch_id`),
  INDEX `fk_bigMatch_bigMatchSerie1_idx` (`bigMatchSerie_id` ASC),
  INDEX `fk_bigMatch_matchSetting1_idx` (`matchSetting_id` ASC),
  INDEX `fk_bigMatch_exchangeRate1_idx` (`exchangeRate_id` ASC),
  CONSTRAINT `fk_bigMatch_bigMatchSerie1`
    FOREIGN KEY (`bigMatchSerie_id`)
    REFERENCES `saishibao`.`bigMatchSerie` (`bigMatchSerie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bigMatch_matchSetting1`
    FOREIGN KEY (`matchSetting_id`)
    REFERENCES `saishibao`.`matchSetting` (`matchSetting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bigMatch_exchangeRate1`
    FOREIGN KEY (`exchangeRate_id`)
    REFERENCES `saishibao`.`exchangeRate` (`exchangeRate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '大赛表';


-- -----------------------------------------------------
-- Table `saishibao`.`bigMatchResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`bigMatchResult` (
  `bigMatchResult_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `result` TEXT NOT NULL COMMENT '大赛结果 json',
  `bigMatch_id` INT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bigMatchResult_id`),
  INDEX `fk_result_bigMatch1_idx` (`bigMatch_id` ASC),
  CONSTRAINT `fk_result_bigMatch1`
    FOREIGN KEY (`bigMatch_id`)
    REFERENCES `saishibao`.`bigMatch` (`bigMatch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '大赛结果表';


-- -----------------------------------------------------
-- Table `saishibao`.`dailyMatchSerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`dailyMatchSerie` (
  `dailyMatchSerie_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '日赛系列名称',
  `organization_id` INT UNSIGNED NOT NULL,
  `hot_level` TINYINT NOT NULL COMMENT '推荐等级：\n1最高，依次 2 3 4，默认5',
  `need_show` TINYINT(1) NOT NULL COMMENT '1:显示在app\n0:不显示',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dailyMatchSerie_id`),
  INDEX `fk_dailyMatchSerie_organization1_idx` (`organization_id` ASC),
  CONSTRAINT `fk_dailyMatchSerie_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `saishibao`.`organization` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '日赛系列';


-- -----------------------------------------------------
-- Table `saishibao`.`dailyMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`dailyMatch` (
  `dailyMatch_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dailyMatchSerie_id` INT ZEROFILL NOT NULL,
  `matchSetting_id` INT UNSIGNED NOT NULL,
  `match_day` VARCHAR(45) NOT NULL,
  `start_time` TIME NOT NULL,
  `close_reg_time` TIME NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT '单笔报名费',
  `state` TINYINT NOT NULL COMMENT '比赛状态',
<<<<<<< HEAD
  `style` VARCHAR(30) NOT NULL COMMENT '比赛类型',
  `remark` VARCHAR(50) NULL COMMENT '备注信息',
=======
>>>>>>> origin/master
  `last_update` TIMESTAMP NOT NULL DEFAULT   CURRENT_TIMESTAMP,
  PRIMARY KEY (`dailyMatch_id`),
  INDEX `fk_dailyMatch_dailyMatchSerie1_idx` (`dailyMatchSerie_id` ASC),
  INDEX `fk_dailyMatch_matchSetting1_idx` (`matchSetting_id` ASC),
  CONSTRAINT `fk_dailyMatch_dailyMatchSerie1`
    FOREIGN KEY (`dailyMatchSerie_id`)
    REFERENCES `saishibao`.`dailyMatchSerie` (`dailyMatchSerie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dailyMatch_matchSetting1`
    FOREIGN KEY (`matchSetting_id`)
    REFERENCES `saishibao`.`matchSetting` (`matchSetting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '日赛表';


-- -----------------------------------------------------
-- Table `saishibao`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单总额＝( unite_price * quantity)',
  `user_id` INT UNSIGNED NOT NULL,
  `bigMatch_id` INT UNSIGNED NULL,
  `dailyMatch_id` INT UNSIGNED NULL,
  `order_No` VARCHAR(30) NOT NULL COMMENT '订单号',
  `quantity` INT NOT NULL COMMENT '购买的数量，对应orderDetail里的记录数',
  `have_pay` TINYINT(1) NOT NULL COMMENT '是否已经付款',
  `rel_discount` DECIMAL(7,2) NOT NULL DEFAULT 1 COMMENT '相对折扣，比如0.95，就是打95折\n',
  `abs_discount` DECIMAL(7,2) NOT NULL DEFAULT 0 COMMENT '绝对折扣，就是立减价格',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '订单总额 = (unite_price*quantity)*rel_discount - abs_discount',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  INDEX `fk_order_bigMatch1_idx` (`bigMatch_id` ASC),
  INDEX `fk_order_dailyMatch1_idx` (`dailyMatch_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `saishibao`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_bigMatch1`
    FOREIGN KEY (`bigMatch_id`)
    REFERENCES `saishibao`.`bigMatch` (`bigMatch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_dailyMatch1`
    FOREIGN KEY (`dailyMatch_id`)
    REFERENCES `saishibao`.`dailyMatch` (`dailyMatch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`orderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`orderDetail` (
  `orderDetail_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `have_createSerial` VARCHAR(45) NOT NULL COMMENT '是否已经生成系列号',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderDetail_id`),
  INDEX `fk_orderDetail_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_orderDetail_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `saishibao`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`payment` (
  `orderPayment_id` INT ZEROFILL UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  `payment_No` VARCHAR(40) NOT NULL COMMENT '支付单号',
  `certificate` VARCHAR(40) NOT NULL COMMENT '支付凭证号',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '实际支付总额',
  `state` TINYINT NOT NULL,
  `pay_type` TINYINT NOT NULL COMMENT '1:微信\n2:支付宝\n3:账户余额',
  `pay_datetime` DATETIME NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderPayment_id`),
  INDEX `fk_payment_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_payment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `saishibao`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`dailyMatchResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`dailyMatchResult` (
  `dailyMatchResult_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `result` TEXT NOT NULL COMMENT '日赛结果 json',
  `dailyMatch_id` INT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dailyMatchResult_id`),
  INDEX `fk_dailyMatchResult_dailyMatch1_idx` (`dailyMatch_id` ASC),
  CONSTRAINT `fk_dailyMatchResult_dailyMatch1`
    FOREIGN KEY (`dailyMatch_id`)
    REFERENCES `saishibao`.`dailyMatch` (`dailyMatch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '日赛结果表';


-- -----------------------------------------------------
-- Table `saishibao`.`serialNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`serialNumber` (
  `serialNumber` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `orderDetail` INT UNSIGNED NOT NULL,
  `have_used` TINYINT(1) NOT NULL COMMENT '序列号是否已å使用',
  `used_time` DATETIME NOT NULL,
  `dailyMatchSerie_id` INT UNSIGNED NULL,
  `bigMatchSerie_id` INT UNSIGNED NULL,
  `valid` TINYINT NOT NULL COMMENT '序列号是否过期\n1，未过期\n0，过期',
  `create_time` DATETIME NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`serialNumber`),
  INDEX `fk_serialNumber_user1_idx` (`user_id` ASC),
  INDEX `fk_serialNumber_orderDetail1_idx` (`orderDetail` ASC),
  INDEX `fk_serialNumber_dailyMatchSerie1_idx` (`dailyMatchSerie_id` ASC),
  INDEX `fk_serialNumber_bigMatchSerie1_idx` (`bigMatchSerie_id` ASC),
  CONSTRAINT `fk_serialNumber_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `saishibao`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serialNumber_orderDetail1`
    FOREIGN KEY (`orderDetail`)
    REFERENCES `saishibao`.`orderDetail` (`orderDetail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serialNumber_dailyMatchSerie1`
    FOREIGN KEY (`dailyMatchSerie_id`)
    REFERENCES `saishibao`.`dailyMatchSerie` (`dailyMatchSerie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serialNumber_bigMatchSerie1`
    FOREIGN KEY (`bigMatchSerie_id`)
    REFERENCES `saishibao`.`bigMatchSerie` (`bigMatchSerie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saishibao`.`userPoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`userPoint` (
  `userPoint_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_point` INT NOT NULL COMMENT '增加积分',
  `user_id` INT UNSIGNED NOT NULL,
  `serialNumber_serialNumber` INT NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userPoint_id`),
  INDEX `fk_userPoint_user1_idx` (`user_id` ASC),
  INDEX `fk_userPoint_serialNumber1_idx` (`serialNumber_serialNumber` ASC),
  CONSTRAINT `fk_userPoint_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `saishibao`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userPoint_serialNumber1`
    FOREIGN KEY (`serialNumber_serialNumber`)
    REFERENCES `saishibao`.`serialNumber` (`serialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户消费积分表';


-- -----------------------------------------------------
-- Table `saishibao`.`globalSetting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`globalSetting` (
  `globalSetting_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '全局配置表\n用于保存一些设置，比如门票过期时间等',
  `var_name` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL DEFAULT 0 COMMENT '0:null\n1:int\n2:double\n3:text\n4:datatime',
  `value_int` INT NULL,
  `value_double` DOUBLE NULL,
  `value_text` TEXT NULL,
  `value_datatime` DATETIME NULL,
  `globalSettingcol` VARCHAR(45) NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`globalSetting_id`))
ENGINE = InnoDB
COMMENT = '全局设置表';


<<<<<<< HEAD
-- -----------------------------------------------------
-- Table `saishibao`.`casinoVip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saishibao`.`casinoVip` (
  `casinoVip_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `casino_id` INT UNSIGNED NOT NULL,
  `vip_No` VARCHAR(45) NULL COMMENT 'vip卡号',
  `user_user_id` INT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`casinoVip_id`),
  INDEX `fk_casinoVip_casino1_idx` (`casino_id` ASC),
  INDEX `fk_casinoVip_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_casinoVip_casino1`
    FOREIGN KEY (`casino_id`)
    REFERENCES `saishibao`.`casino` (`casino_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_casinoVip_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `saishibao`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '俱乐部会员卡';


=======
>>>>>>> origin/master
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
